-- CreateTable
CREATE TABLE "Project" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL,
    "projectName" TEXT NOT NULL,
    "country" TEXT NOT NULL,
    "locationDescription" TEXT NOT NULL,
    "technologyType" TEXT NOT NULL,
    "capacityKw" REAL,
    "targetBeneficiaries" TEXT NOT NULL,
    "ownershipModel" TEXT NOT NULL,
    "productiveUses" TEXT NOT NULL,
    "estimatedCostUsd" REAL NOT NULL,
    "existingFunding" TEXT,
    "projectStage" TEXT NOT NULL,
    "communityEngagement" TEXT,
    "additionalContext" TEXT,
    "debtPreference" TEXT NOT NULL,
    "policyResult" TEXT,
    "grantsResult" TEXT,
    "coachResult" TEXT,
    "m300Score" INTEGER,
    "debtTier" TEXT,
    "topFunder" TEXT,
    "topFunderScore" INTEGER,
    "enhanced" BOOLEAN NOT NULL DEFAULT false,
    "processingTimeMs" INTEGER,
    "status" TEXT NOT NULL DEFAULT 'submitted',
    "advisorNotes" TEXT,
    "submittedBy" TEXT
);
